### ISSUE TITLE
Does not support java 9

### ISSUE THREAD

**Issue by mhaddon** [grzegorz-wolszczak/kafka-message-tool#20]
`
00:23:22.728 [Error]: Error while starting application
java.lang.NoClassDefFoundError: javax/xml/bind/UnmarshalException
        at application.root.KafkaMessageToolApplication.createObjects(KafkaMessageToolApplication.java:125)
        at application.root.KafkaMessageToolApplication.start(KafkaMessageToolApplication.java:66)
        at application.Main.start(Main.java:24)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:919)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(PlatformImpl.java:449)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.UnmarshalException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 9 more
`

**Comment by grzegorz-wolszczak** [comment]
You could try to compile from branch java10-port , after that you must run the jar with command

`java --add-opens java.base/java.lang=ALL-UNNAMED --add-modules=java.xml.bind,java.activation -jar .\kafka-message-tool-1.0.4.0-java10.jar`
